#ifndef DEFINITIONS_H
#define DEFINITIONS_H 

// MMAL INDEX FOR CAMERA COMPONENT
#define MMAL_CAMERA_PREVIEW_PORT 0
#define MMAL_CAMERA_VIDEO_PORT 1
#define MMAL_CAMERA_CAPTURE_PORT 2


// IMAGE FEATURES
#define CARE_RENDER_IMG_WIDTH	1280
#define CARE_RENDER_IMG_HEIGHT	720
#define CARE_VIDEO_IMG_WIDTH	1280
#define CARE_VIDEO_IMG_HEIGHT 	720
#define CARE_SCALEDOWN_IMG		4	// to scale down the original image

#endif